language: python

python:
  # - 2.7
  - 3.6

before_script:
  - python setup.py install

script:
  - entree python blah
  # - python -m unittest discover tests/

notifications:
  email:
    on_success: never
    on_failure: never