language: python

python:
  - 2.7
  - 3.6

before_script:
  - python setup.py install

script:
  - python -m unittest discover tests/ -p "test_*.py"
  - python tests/entree_bash_test.py

notifications:
  email:
    on_success: never
    on_failure: never