language: python

python:
  - 3.12.7

# install:
#   - pip install pylint

before_script:
  - python setup.py install

script:
  # - pylint entree
  - python -m unittest discover tests/ -p "test_*.py"
  - python tests/entree_bash_test.py

notifications:
  email:
    on_success: never
    on_failure: never